baseURL = 'https://stradex.github.io/my-thoughts/'
languageCode = 'en-us'
title = 'Stradex personal notebook'
theme = 'hugo-theme-console-dark'
[services]
  [services.disqus]
    shortname = 'stradex'
